databases:
  - name: buscatronics
    databaseName: buscatronics
    user: buscatronics_user

services:
  - type: web
    name: buscatronics
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn buscatronics.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: buscatronics
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4