# Generated by Django 4.2.6 on 2023-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='link',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='produto',
            name='precoTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
